#!/usr/bin/env python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2023-2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Authors: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
#          Niklas Neronin <niklas.neronin@intel.com>

"""
Detect I/O scope of a writable Model-Specific Register (MSR). Refer to 'docs/misc-msr-scope.md' for
more information about MSR I/O scope.
"""

from pepctools._MSRIOScope import main

if __name__ == "__main__":
    raise SystemExit(main())
