#!/usr/bin/env python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2020-2022 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Niklas Neronin <niklas.neronin@intel.com>

"""Common functions for the 'CStates' and 'PStates' class tests."""

def get_fellows(params, cpuinfo, cpu=0):
    """
    Return a dict with keys being scopes and values being all fellow CPUs (CPUs sharing the same
    scope as a CPU) to the CPU 'cpu'. The dict is used when running tests with function calls that
    require a list of CPUs with the same scope as the CPU that we are changing the value of.

    The argument are as follows.
     * params - Various common parameters for running the tests.
     * cpuinfo - CPU information object generated by 'CPUInfo.CPUInfo()'.
     * cpu - the CPU whose fellows we return.
    """

    levels = cpuinfo.get_cpu_levels(cpu)

    fellows = {}
    fellows["global"] = params["cpus"]
    fellows["package"] = cpuinfo.package_to_cpus(levels["package"])
    fellows["die"] = cpuinfo.dies_to_cpus(dies=levels["die"], packages=levels["package"])
    # No fellows['node'], because there is currently no property with 'node' scope.
    fellows["core"] = cpuinfo.cores_to_cpus(cores=levels["core"], packages=levels["package"])
    fellows["CPU"] = cpu

    return fellows

def set_and_verify(pcobj, pname, value, cpus):
    """
    Set property 'pname' to value 'value' for CPUs in 'cpus', then read it back and verify that the
    read value is 'value'.

    The argument are as follows.
     * pcobj - 'CStates' or 'PStates' object.
     * pname - name of the property.
     * value - the new value.
     * cpus - list of CPUs.
    """

    pcobj.set_prop(pname, value, cpus)

    for cpu, pinfo in pcobj.get_props((pname, ), cpus):
        if pinfo[pname][pname] != value:
            assert False, f"Failed to set property '{pname}' for CPU {cpu}\nSet to '{value}' and " \
                          f"received '{pinfo[pname][pname]}'."
