# Name of the workflow, visible in the GitHub Actions UI
name: "CI public"
# Define the events that trigger this workflow
on:
  # Trigger on push events
  push:
    branches:
      - "main"

  # Trigger on pull request events
  pull_request:
    branches:
      - "main"

# Define the jobs to run in this workflow
jobs:
  mypy:
    if: ${{ github.repository_owner != 'intel-innersource' }}
    uses: ./.github/workflows/mypy.yml

  pylint:
    if: ${{ github.repository_owner != 'intel-innersource' }}
    uses: ./.github/workflows/pylint.yml

  ruff:
    if: ${{ github.repository_owner != 'intel-innersource' }}
    uses: ./.github/workflows/ruff.yml

  pytest:
    if: ${{ github.repository_owner != 'intel-innersource' }}
    uses: ./.github/workflows/pytest.yml
